/**
 * The workbook, as data. `exceljs` never appears here — the writer is a separate script.
 *
 * Keeping the sheet contents as plain cells means a test can walk every cell and assert
 * that no number arrived without provenance (see workbookProvenance.test.ts), which is the
 * control that turns "no made-up numbers" from a promise into a failing build.
 */
import { REGISTER } from './assumptions';
import {
  METRO_ASSUMPTIONS,
  METROS,
  MODEL_YEARS,
  addressableVenues,
  addressableBand,
  describeAddressable,
  totalFoodServiceVenues,
  ADDRESSABLE_NAICS,
  ADDRESSABLE_BUCKETS,
  enabledMetros,
} from './metros';
import { loadCensusSnapshot, snapshotFor } from './censusTam';
import { projectMetroYear, metroKpis, blendedCac, MONTHS_PER_YEAR } from './metroModel';
import {
  rollup,
  COHORT_METRO_COUNTS,
  COHORT_METRO_ID,
  COHORT_TEMPLATE_METRO_ID,
} from './rollup';
import { consolidated, sharedCostForYear } from './consolidated';
import {
  REGISTERED_MIX,
  TIERS,
  avgCampaignValue,
  blendedSubscription,
  blendedTakeRate,
  revenuePerCustomerMonth,
} from './project';
import { unitEconomics } from './derive';
import {
  PRE_SEED_BUDGET,
  PRE_SEED_HORIZON_MONTHS,
  budgetTotal,
  preSeedRaise,
  buildFundsAllocation,
  USE_OF_FUNDS_SPLIT,
  CONFIDENTIAL_ASSUMPTIONS,
} from './confidential';
import type { Assumption } from './types';

export interface Cell {
  readonly v: string | number | null;
  /** Excel formula, without the leading `=`. Task 7 fills these in. */
  readonly f?: string;
  /** Defined name for this cell, so formulas elsewhere can reference it by name. */
  readonly name?: string;
  /** Excel number format, e.g. `'$#,##0'` or `'0.0%'`. */
  readonly fmt?: string;
}

export type CellRow = readonly Cell[];

export interface SheetSpec {
  readonly name: string;
  readonly rows: readonly CellRow[];
}

export const FINANCING_SHEET = 'Financing';

export const SHEET_ORDER = [
  'README',
  'Assumptions',
  'Sources',
  'Hoboken_Model',
  'Manhattan_Model',
  'PalmBeach_Model',
  'MontaukHamptons_Model',
  'Metros_4toN',
  'Shared_Costs',
  'Totals',
  'Unit_Economics',
  FINANCING_SHEET,
] as const;

const t = (v: string): Cell => ({ v });
const n = (v: number, fmt = '$#,##0'): Cell => ({ v, fmt });
const pct = (v: number): Cell => ({ v, fmt: '0.0%' });
const blank: Cell = { v: null };

/**
 * The defined name a registered assumption is published under, and the ONLY way a formula
 * should ever spell one. Definition and reference both call this, so they cannot drift.
 *
 * The sanitisation is not cosmetic. Metro ids carry a hyphen (`palm-beach`,
 * `montauk-hamptons`), and a hyphen is illegal in an Excel defined name; worse, the formula
 * tokenizer in formulaEval.ts would read `asm_palm-beach_penetration_2026` as `asm_palm`
 * MINUS `beach_penetration_2026` — a formula that parses, resolves nothing, and throws at
 * evaluation. Two of the four metros are affected, so the first reference to a penetration
 * cell would have failed.
 */
function asmName(key: string): string {
  return `asm_${key.replace(/[^A-Za-z0-9_]/g, '_')}`;
}

/**
 * Named cells on Unit_Economics holding quantities that are DERIVED from the tier mix and
 * pricing rather than registered as assumptions. See `unitEconomicsSheet`.
 */
const UE = {
  blendedSubscription: 'ue_blendedSubscription',
  blendedTakeRate: 'ue_blendedTakeRate',
  avgCampaignValue: 'ue_avgCampaignValue',
  arpuPerCustomerMonth: 'ue_arpuPerCustomerMonth',
  cac: 'ue_cac',
} as const;

const SHEET_BY_METRO: Readonly<Record<string, string>> = {
  hoboken: 'Hoboken_Model',
  manhattan: 'Manhattan_Model',
  'palm-beach': 'PalmBeach_Model',
  'montauk-hamptons': 'MontaukHamptons_Model',
};

/**
 * `confidentialAssumptions` is included only for the confidential build. The Assumptions sheet
 * ships in BOTH builds, so putting founder salaries / use-of-funds shares here unconditionally
 * would leak them into the public workbook the same way `FINANCING_SHEET` is gated instead.
 */
function assumptionRows(confidential: boolean): CellRow[] {
  const all: Array<[string, Assumption<number>]> = [
    ...Object.entries(REGISTER),
    ...Object.entries(METRO_ASSUMPTIONS),
    ...MODEL_YEARS.map((y) => [`cohortMetros_${y}`, COHORT_METRO_COUNTS[y]] as [string, Assumption<number>]),
    ...(confidential ? Object.entries(CONFIDENTIAL_ASSUMPTIONS) : []),
  ];
  return all.map(([key, a]) => [
    t(key),
    t(a.label),
    { v: a.value, name: asmName(key) },
    t(a.provenance),
    t(a.source),
    t(a.provenance === 'MEASURED' ? a.asOf : ''),
    t(a.unit),
    t(a.note ?? ''),
  ]);
}

function readmeSheet(): SheetSpec {
  return {
    name: 'README',
    rows: [
      [t('DragonCandy — three-year financial model')],
      [t('Generated by `npm run model:xlsx`. Do not edit by hand; the next run overwrites it.')],
      [blank],
      // This paragraph has been wrong in both directions and the history is worth keeping.
      // It first said "Every input lives on the Assumptions sheet as a named cell ... Nothing
      // else holds a raw number", which was never true. It was corrected to a smaller claim —
      // and the smaller claim was ALSO not true, because no formula referenced a named cell at
      // all: the whole Assumptions sheet was inert, and "change one and the model reflows" was
      // advice that did nothing. So state the mechanism and then name every exception, because
      // a reader who checks one claim and finds it false stops trusting the sheets that work.
      [t('Pricing, the tier mix, campaign volume and value, Stripe and serving costs, CAC, the')],
      [t('per-metro penetrations and the cohort metro count are named cells on the Assumptions')],
      [t('sheet, and the metro sheets, the cohort sheet and the Totals rollup are formulas over')],
      [t('them. Change one and the numbers that depend on it recalculate. Unit_Economics holds')],
      [t('the blends derived from those cells (ARPU, blended take rate, average campaign value,')],
      [t('CAC) — also formulas, so they move too.')],
      [blank],
      [t('FOUR THINGS ARE DELIBERATELY PLAIN VALUES, and each says so where it appears:')],
      [t('  Customer-months — the sum of customers across a year’s twelve months. The monthly')],
      [t('    ramp is not on the sheet, so this cannot be recomputed from a year-end figure.')],
      [t('  Gross adds — the same, for churn replaced month by month.')],
      [t('  Addressable venues — a Census count (see Sources), not an assumption to edit.')],
      [t('  Shared cost — company-level, from outside the metro sheets entirely.')],
      [t('Because customer-months is fixed, editing a PENETRATION moves customers at year end')],
      [t('and Exit ARR but not booked revenue. Re-run `npm run model:xlsx` after such an edit.')],
      [blank],
      [t('Provenance: MEASURED = read off production, an invoice or the codebase on the stated')],
      [t('date, with the command that re-reads it. BENCHMARKED = an external comparable, with a')],
      [t('URL. MODELED = ours, with the driver named. See the Assumptions and Sources sheets.')],
      [blank],
      [t('Toggle a metro in or out with the YES/NO cells on Totals.')],
    ],
  };
}

function sourcesSheet(): SheetSpec {
  const snap = loadCensusSnapshot();
  const rows: CellRow[] = [
    [t('Sources')],
    [blank],
    [t('Market size — US Census Business Patterns')],
    [t('NAICS in the addressable band'), t(ADDRESSABLE_NAICS.join(', '))],
    [t('Employment-size buckets'), t(ADDRESSABLE_BUCKETS.join(', '))],
    [t('Excluded: 722513 limited-service'), t('franchised fast food — social is set at corporate, not by the location')],
    [t('Excluded: 7223 special food services'), t('catering and food trucks — no fixed venue to market')],
    [t('Excluded: under 5 employees'), t('below the $149 entry tier’s plausible budget')],
    [t('Excluded: 50+ employees'), t('has, or is owned by someone who has, a marketing function')],
    [blank],
  ];
  for (const m of snap.metros) {
    rows.push([t(m.metroId), t(m.geography.label), t(`vintage ${m.vintage}`), t(m.sourceUrl), t(`fetched ${m.fetchedAt}`)]);
    // Written, not printed as a bare number: where the count is a floor this is the only
    // place a reader learns it. `describeAddressable` owns the wording for every surface.
    rows.push([blank, t(describeAddressable(m.metroId))]);
    if (m.parts) {
      const answered = m.parts.filter((p) => p.rows.length > 0).length;
      rows.push([
        blank,
        t(
          `${m.parts.length} constituent ZIPs, of which ${answered} appear in the ZBP at all. ` +
            `The rest are ABSENT, which is not the same as zero and is recorded rather than dropped:`,
        ),
      ]);
      for (const p of m.parts) {
        const row722 = p.rows.find((r) => r.naics === '722');
        rows.push([
          blank,
          t(`${p.code} ${p.label}`),
          t(row722 ? `${row722.establishments} food service venues` : 'ABSENT — no ZBP rows'),
        ]);
      }
    }
  }
  rows.push(
    [blank],
    [t('Census suppression')],
    [t('Cells marked "N" are suppressed to protect respondent confidentiality. They are treated')],
    [t('as unknown, never as zero. A bucket forced by the establishment total is recovered as')],
    [t('the residual; where more than one is suppressed the model states a range.')],
    [t('ON THIS 2023 VINTAGE NOTHING IS RECOVERABLE, and we would rather you read that here than')],
    [t('find it yourself. A bucket is forced only when exactly one of a row’s nine is unknown.')],
    [t('Across all 67 rows in our snapshot the fewest any row has is TWO — the distribution runs')],
    [t('2 to 9 — so ZERO rows qualify and the recovery step changes no number in this workbook.')],
    [t('Every addressable count here is therefore a floor, and "suppressed cells" is the whole')],
    [t('story. The recovery step is kept because a later vintage or a narrower geography can')],
    [t('produce a one-unknown row; it runs PER GEOGRAPHY and BEFORE any summing, since summing')],
    [t('first would pool several rows’ unknowns and lose a recoverable bucket for nothing.')],
    [t('Across a SET of ZIPs the addressable count is then a FLOOR — the sum of what is known —')],
    [t('rather than a refusal. Refusing is right for one geography (a hidden cell means the metro')],
    [t('is not modelable, which is why Palm Beach moved from the town ZIP to the county); across')],
    [t('fourteen ZIPs it would make a real market unmodelable over one hidden count in one hamlet.')],
    [t('The bias is bounded, one-directional and stated: it can only UNDERSTATE, never overstate.')],
    [blank],
    [t('Rows in Adrian’s model that are OMITTED here, deliberately')],
    [t('Bonus costs'), t('no analogue — DragonCandy discounts nothing')],
    [t('Statutory gaming tax'), t('no analogue — not a gaming business')],
    [t('Market access fees'), t('no analogue — no licence holder takes a share')],
    [t('A row shaped like his but filled with an invented number would be worse than its absence.')],
    [blank],
    [t('Every other number traces to the Assumptions sheet, which carries its provenance and source.')],
  );
  return { name: 'Sources', rows };
}

/** This metro sheet's own year columns — label in A, so years land in B/C/D. */
const METRO_YEAR_COLS = ['B', 'C', 'D'] as const;

function metroSheet(metroId: string): SheetSpec {
  const snap = snapshotFor(loadCensusSnapshot(), metroId);
  const years = MODEL_YEARS.map((y) => projectMetroYear(metroId, y, REGISTERED_MIX));
  const label = METROS.find((m) => m.id === metroId)!.label;
  const sheetName = SHEET_BY_METRO[metroId];
  // Every reference is sheet-qualified, even these same-sheet ones — see formulaEval.ts's
  // header comment for why the evaluator requires that.
  const ref = (row: number, col: string) => `${sheetName}!${col}${row}`;

  const line = (name: string, pick: (y: (typeof years)[number]) => number, fmt?: string): CellRow => [
    t(name),
    ...years.map((y) => (fmt === '0.0%' ? pct(pick(y)) : n(pick(y), fmt))),
  ];

  /**
   * The same row, but LIVE: the model's number as the cached value and a formula that must
   * reproduce it. `formulaAgreement.test.ts` checks every one of these, so a driver row that
   * is quietly converted back to a plain value loses its check silently — which is why the
   * assumption-reachability test in workbook.test.ts asserts the references exist by name.
   */
  const liveLine = (
    name: string,
    pick: (y: (typeof years)[number]) => number,
    formula: (i: number) => string,
    fmt = '$#,##0',
  ): CellRow => [
    t(name),
    ...MODEL_YEARS.map((_, i) => ({ v: pick(years[i]), f: formula(i), fmt })),
  ];

  const col = (i: number) => METRO_YEAR_COLS[i];

  // Rows are pushed in order and their Excel row numbers (rows.length after each push)
  // captured as we go, so a formula can reference an earlier row without hardcoding its
  // index — the same discipline totalsSheet() below uses.
  const rows: CellRow[] = [
    [t(label), ...MODEL_YEARS.map((y) => t(String(y)))],
    [t(`${snap.geography.label} — Census ${snap.vintage}`)],
    [blank],
    [t('Market')],
    [t('Total food service venues'), ...years.map(() => n(totalFoodServiceVenues(metroId), '#,##0'))],
    // The disclosure rides in a trailing cell on the SAME row as the number, never on a row
    // of its own: a new row here would shift every row index below it, and totalsSheet()'s
    // REVENUE_ROW / EBITDA_ROW maps address this sheet by number. It is `describeAddressable`
    // that decides the wording, so no surface can print a floor as if it were a count.
    [
      t('Addressable venues'),
      ...years.map(() => n(addressableVenues(metroId), '#,##0')),
      // Two things ride in this trailing cell, on the SAME row as the number (a row of its own
      // would shift every index below it). First the suppression disclosure, where there is
      // one. Then, always, why this row is a plain value while the rows below it are live:
      // there is no assumption cell to point at. The count is derived from the Census
      // snapshot in censusTam.json by the NAICS/employment-size filter the Sources sheet
      // spells out — it is evidence, not a dial, and it is the one input a reader is not
      // invited to edit.
      t(
        (addressableBand(metroId).suppressedCells === 0 ? '' : `${describeAddressable(metroId)} `) +
          'Plain value, not a formula: this count comes from the Census snapshot (see Sources), ' +
          'not from an assumption cell, so there is nothing on the Assumptions sheet to reference.',
      ),
    ],
  ];
  const addressableRow = rows.length;
  // Live off the metro's own registered penetration anchor for that year. `penetrationAtMonth`
  // interpolates between anchors, and a year END is exactly an anchor month, so the two agree
  // by construction (Hoboken 2027 differs in the last bit of a double — 0.22000000000000003
  // against 0.22 — which is why the agreement test compares within a tolerance rather than
  // for equality).
  rows.push(
    liveLine(
      'Penetration of addressable',
      (y) => y.penetrationAtYearEnd,
      (i) => asmName(`${metroId}_penetration_${MODEL_YEARS[i]}`),
      '0.0%',
    ),
  );
  const penetrationRow = rows.length;

  // Customers at year end = ROUND(addressable * penetration, 0) — matches
  // `customersAtMonth`'s `Math.round`, which a plain product does not (they can differ by up
  // to ~0.4 for these metros). See formulaEval.ts's header comment.
  rows.push([
    t('Customers at year end'),
    ...MODEL_YEARS.map((_, i) => ({
      v: years[i].customersAtYearEnd,
      f: `ROUND(${ref(addressableRow, METRO_YEAR_COLS[i])}*${ref(penetrationRow, METRO_YEAR_COLS[i])},0)`,
      fmt: '#,##0',
    })),
  ]);

  const customersRow = rows.length;

  // The two MONTHLY INTEGRALS, and the only driver rows on this sheet that stay plain values.
  // Everything below is arithmetic over them, so they are where the model has to be trusted
  // and the rest is a reader's own multiplication.
  rows.push(line('Customer-months', (y) => y.customerMonths, '#,##0.0'));
  const customerMonthsRow = rows.length;
  rows.push(line('Gross adds (incl. churn replacement)', (y) => y.grossAdds, '#,##0'));
  const grossAddsRow = rows.length;
  rows.push([
    t('Customer-months sums customers across the year’s twelve months and gross adds sums the'),
  ]);
  rows.push([
    t('churn replaced in each of them. Neither is recoverable from a year-end figure, so both'),
  ]);
  rows.push([t('are carried from the model. Every row below is computed from one of them.')]);
  // The one partial answer in this workbook, disclosed where a reader meets it rather than
  // left to be discovered by editing a cell and watching half the sheet move. Pinned by
  // workbookLiveness.test.ts, which asserts both halves of the behaviour AND this wording.
  rows.push([
    t('EDITING PENETRATION IS THE ONE PARTIAL CASE. It re-drives customers at year end and'),
  ]);
  rows.push([
    t('therefore Exit ARR, but NOT customer-months — a year-end share cannot reconstruct a'),
  ]);
  rows.push([
    t('twelve-month ramp — so booked revenue and the cost rows below will not move. Re-run'),
  ]);
  rows.push([t('`npm run model:xlsx` after changing a penetration. Every other input is fully live.')]);

  rows.push([blank]);
  rows.push([t('Revenue')]);
  rows.push(
    liveLine(
      'Campaigns',
      (y) => y.campaigns,
      (i) => `${ref(customerMonthsRow, col(i))}*${asmName('campaignsPerRestaurantPerMonth')}`,
      '#,##0',
    ),
  );
  const campaignsRow = rows.length;
  rows.push(
    liveLine('GMV', (y) => y.gmv, (i) => `${ref(campaignsRow, col(i))}*${UE.avgCampaignValue}`),
  );
  const gmvRow = rows.length;
  rows.push(
    liveLine(
      'Subscription revenue',
      (y) => y.subscriptionRevenue,
      (i) => `${ref(customerMonthsRow, col(i))}*${UE.blendedSubscription}`,
    ),
  );
  const subscriptionRow = rows.length;
  rows.push(
    liveLine(
      'Take-rate revenue',
      (y) => y.takeRateRevenue,
      (i) => `${ref(gmvRow, col(i))}*${UE.blendedTakeRate}`,
    ),
  );
  const takeRateRow = rows.length;

  rows.push([
    t('Total revenue'),
    ...MODEL_YEARS.map((_, i) => ({
      v: years[i].revenue,
      f: `${ref(subscriptionRow, METRO_YEAR_COLS[i])}+${ref(takeRateRow, METRO_YEAR_COLS[i])}`,
      fmt: '$#,##0',
    })),
  ]);
  const totalRevenueRow = rows.length;

  // Exit ARR beside booked revenue, because the two are different quantities and a sheet
  // that shows only one invites the reader to treat it as the other.
  //
  // This was a plain value on the argument that a live formula would need ARPU as a cell and
  // ARPU is DERIVED from the tier mix rather than being an assumption. The premise was right
  // and the conclusion was wrong: a derived quantity does not belong on the ASSUMPTIONS sheet,
  // but it belongs perfectly well on Unit_Economics as a formula over the assumption cells,
  // which is where `ue_arpuPerCustomerMonth` now is. The `12` is the calendar — see
  // ALLOWED_LITERALS in workbookProvenance.test.ts.
  rows.push(
    liveLine(
      'Exit ARR (year-end run rate)',
      (y) => y.exitArr,
      (i) => `${ref(customersRow, col(i))}*${UE.arpuPerCustomerMonth}*${MONTHS_PER_YEAR}`,
    ),
  );
  rows.push([
    t('Booked revenue is summed month by month while customers ramp; exit ARR is year-end'),
  ]);
  rows.push([t('customers at a full year of the registered mix. They are not comparable.')]);

  rows.push([blank]);
  rows.push([t('Cost of revenue')]);
  // Negative, like every cost row here — "Total cost of revenue" and "Gross profit" below ADD
  // them. The leading minus is on the whole bracket rather than distributed, so the formula
  // reads as "the cost, made negative" rather than as a subtraction of two positives.
  rows.push(
    liveLine(
      'Stripe fees',
      (y) => -y.stripeCost,
      (i) =>
        `-(${ref(gmvRow, col(i))}*${asmName('stripePctFee')}` +
        `+${ref(campaignsRow, col(i))}*${asmName('stripeFixedFee')})`,
    ),
  );
  const stripeRow = rows.length;
  rows.push(
    liveLine(
      'AI and infrastructure',
      (y) => -y.serveCost,
      (i) =>
        `-(${ref(customerMonthsRow, col(i))}*(${asmName('aiCostPerCustomerMonth')}` +
        `+${asmName('infraCostPerCustomerMonth')}))`,
    ),
  );
  const aiRow = rows.length;

  rows.push([
    t('Total cost of revenue'),
    ...MODEL_YEARS.map((_, i) => ({
      v: -years[i].costOfRevenue,
      f: `${ref(stripeRow, METRO_YEAR_COLS[i])}+${ref(aiRow, METRO_YEAR_COLS[i])}`,
      fmt: '$#,##0',
    })),
  ]);
  const totalCostRow = rows.length;

  rows.push([
    t('Gross profit'),
    ...MODEL_YEARS.map((_, i) => ({
      v: years[i].grossProfit,
      // Cost rows are already negative, so this is addition, not subtraction.
      f: `${ref(totalRevenueRow, METRO_YEAR_COLS[i])}+${ref(totalCostRow, METRO_YEAR_COLS[i])}`,
      fmt: '$#,##0',
    })),
  ]);
  const grossProfitRow = rows.length;

  rows.push([blank]);
  rows.push([t('Marketing')]);
  // Charged on GROSS adds, not net growth — see `projectMetroYear`. `ue_cac` is the midpoint
  // of the registered low/high band, so editing either end of the band moves this row.
  rows.push(
    liveLine(
      'Acquisition marketing',
      (y) => -y.marketingCost,
      (i) => `-(${ref(grossAddsRow, col(i))}*${UE.cac})`,
    ),
  );
  const marketingRow = rows.length;

  rows.push([blank]);
  rows.push([
    t('Metro EBITDA'),
    ...MODEL_YEARS.map((_, i) => ({
      v: years[i].metroEbitda,
      f: `${ref(grossProfitRow, METRO_YEAR_COLS[i])}+${ref(marketingRow, METRO_YEAR_COLS[i])}`,
      fmt: '$#,##0',
    })),
  ]);

  rows.push([blank]);
  rows.push([t('KPIs')]);

  // The three ratios divide by "Total revenue", which is 0 in a metro's pre-launch year
  // (Palm Beach, 2026). `metroKpis()` guards that with its own `revenue === 0 ? 0 : …`, so
  // the formula must guard it too, or Excel shows #DIV/0! where the cache shows 0. The
  // marketing / cost-of-revenue source rows are stored negative, hence the leading `-`.
  const revZero = (i: number) => `${ref(totalRevenueRow, METRO_YEAR_COLS[i])}=0`;
  rows.push([
    t('Gross margin'),
    ...MODEL_YEARS.map((_, i) => ({
      v: metroKpis(years[i]).grossMarginPct,
      f: `IF(${revZero(i)},0,${ref(grossProfitRow, METRO_YEAR_COLS[i])}/${ref(totalRevenueRow, METRO_YEAR_COLS[i])})`,
      fmt: '0.0%',
    })),
  ]);
  rows.push([
    t('Marketing as % of revenue'),
    ...MODEL_YEARS.map((_, i) => ({
      v: metroKpis(years[i]).marketingPctOfRevenue,
      f: `IF(${revZero(i)},0,-${ref(marketingRow, METRO_YEAR_COLS[i])}/${ref(totalRevenueRow, METRO_YEAR_COLS[i])})`,
      fmt: '0.0%',
    })),
  ]);
  rows.push([
    t('Cost of revenue as % of revenue'),
    ...MODEL_YEARS.map((_, i) => ({
      v: metroKpis(years[i]).costOfRevenuePctOfRevenue,
      f: `IF(${revZero(i)},0,-${ref(totalCostRow, METRO_YEAR_COLS[i])}/${ref(totalRevenueRow, METRO_YEAR_COLS[i])})`,
      fmt: '0.0%',
    })),
  ]);

  return { name: sheetName, rows };
}

/**
 * The unnamed later metros: N copies of the template metro's own sheet.
 *
 * Every figure here is the TEMPLATE SHEET'S cell times the metro count, which is exactly what
 * `cohortMetroYear` does in TypeScript (`COHORT_SCALED_FIELDS.map(k => template[k] * count)`).
 * Referencing the template's rows rather than re-deriving revenue from customer-months keeps
 * one definition of the ramp: change a tier price and it moves on the template sheet, and this
 * sheet follows because it multiplies that sheet.
 *
 * The count itself is live off `asm_cohortMetros_<year>`, so "how many metros" is editable on
 * the Assumptions sheet the way the prose above has always claimed it was.
 */
function cohortSheet(sourceSheets: readonly SheetSpec[]): SheetSpec {
  const years = rollup().map((r) => r.metros.find((m) => m.metroId === COHORT_METRO_ID)!);
  const templateSheetName = SHEET_BY_METRO[COHORT_TEMPLATE_METRO_ID];
  const template = sourceSheets.find((sheet) => sheet.name === templateSheetName);
  if (!template) {
    // The same failure `cohortMetroYear` guards against, one layer up: a template metro that
    // is disabled or renamed would otherwise leave this sheet silently pointing at nothing.
    throw new Error(
      `The cohort template metro "${COHORT_TEMPLATE_METRO_ID}" has no sheet in this workbook, ` +
        `so Metros_4toN cannot reference it. Enable the metro or pick a new template.`,
    );
  }
  const cref = (row: number, i: number) => `Metros_4toN!${METRO_YEAR_COLS[i]}${row}`;
  const tmplRef = (label: string, i: number) =>
    `${templateSheetName}!${METRO_YEAR_COLS[i]}${rowOf(template, label)}`;

  const rows: CellRow[] = [
    [t('Metros beyond the four named'), ...MODEL_YEARS.map((y) => t(String(y)))],
    [t('These metros have not been chosen. Modeled as N copies of a TEMPLATE metro rather')],
    [t('than as invented named cities. Change the count on the Assumptions sheet.')],
    [t(`Template: ${COHORT_TEMPLATE_METRO_ID} — a real registered metro with real Census`)],
    [t('counts and a ramp appropriate to a market entered in month 12 with no local presence,')],
    [t('which is the situation every metro in this cohort is in. It was Hoboken until')],
    [t('2026-08-26: a one-square-mile town of 123 venues carrying the founders’ home-town 35%')],
    [t('penetration, applied to 17 cities nobody has entered.')],
    [t(`Every row below is the matching ${templateSheetName} row times the count, which is what`)],
    [t('the rollup does in code. Nothing on this sheet is a second derivation of the ramp.')],
    [blank],
    [
      t('Metros in cohort'),
      ...MODEL_YEARS.map((y) => ({
        v: COHORT_METRO_COUNTS[y].value,
        f: asmName(`cohortMetros_${y}`),
        fmt: '#,##0',
      })),
    ],
  ];
  const countRow = rows.length;

  const scaled = (
    label: string,
    templateLabel: string,
    pick: (y: (typeof years)[number]) => number,
    fmt = '$#,##0',
  ): CellRow => [
    t(label),
    ...MODEL_YEARS.map((_, i) => ({
      v: pick(years[i]),
      f: `${tmplRef(templateLabel, i)}*${cref(countRow, i)}`,
      fmt,
    })),
  ];

  rows.push(
    scaled('Customers at year end', 'Customers at year end', (y) => y.customersAtYearEnd, '#,##0'),
    scaled('Revenue', 'Total revenue', (y) => y.revenue),
    scaled('Exit ARR (year-end run rate)', 'Exit ARR (year-end run rate)', (y) => y.exitArr),
    scaled('Gross profit', 'Gross profit', (y) => y.grossProfit),
    // Both sides are already negative: the template's "Acquisition marketing" row is stored
    // negative, and this sheet prints `-marketingCost`. Multiplying by a positive count keeps
    // the sign, so this is not a second negation.
    scaled('Marketing', 'Acquisition marketing', (y) => -y.marketingCost),
    scaled('Metro EBITDA', 'Metro EBITDA', (y) => y.metroEbitda),
  );

  return { name: 'Metros_4toN', rows };
}

function sharedCostsSheet(): SheetSpec {
  const years = consolidated();
  const rows: CellRow[] = [
    [t('Shared costs'), ...MODEL_YEARS.map((y) => t(String(y)))],
    [t('Payroll, AI and shared infrastructure, allocated across metros by revenue share.')],
    [t('Before any metro has revenue the split is even — a revenue-weighted split of zero')],
    [t('is a division by zero, not an allocation.')],
    [blank],
    [t('Total shared cost'), ...MODEL_YEARS.map((y) => n(sharedCostForYear(y)))],
    [blank],
    [t('Allocation')],
  ];
  const metroIds = years[0].allocations.map((a) => a.metroId);
  for (const id of metroIds) {
    rows.push([
      t(id),
      ...years.map((y) => n(y.allocations.find((a) => a.metroId === id)?.amount ?? 0)),
    ]);
  }
  return { name: 'Shared_Costs', rows };
}

/**
 * `SOURCE_COLS` is where a metro or cohort sheet's own years live (label in A, no toggle
 * column, so years are B/C/D). `TOTALS_COLS` is where THIS sheet's years live (label in A,
 * "Include?" toggle in B, so years are C/D/E). A cross-sheet reference (anything after a
 * `!`) always uses `SOURCE_COLS`; anything addressing this sheet's own rows uses
 * `TOTALS_COLS`. Conflating the two was an earlier bug here: it read each metro's NEXT
 * year's revenue instead of its own, and read a trailing empty column as 0.
 */
const SOURCE_COLS = ['B', 'C', 'D'] as const;
const TOTALS_COLS = ['C', 'D', 'E'] as const;

/**
 * The 1-indexed Excel row on `sheet` whose label cell reads `label`.
 *
 * This replaces a hand-maintained map of row numbers per sheet. That map was a trap: adding
 * an explanatory line to the cohort sheet silently shifted every row below it, and the map
 * would have gone on pointing at whatever landed on the old row — a formula reading the
 * wrong figure while its cached value stayed right, which is the one failure mode a live
 * workbook must not have. Both failure directions throw rather than guess.
 */
function rowOf(sheet: SheetSpec, label: string): number {
  const hits = sheet.rows
    .map((row, i) => (row[0]?.v === label ? i + 1 : 0))
    .filter((i) => i > 0);
  if (hits.length !== 1) {
    throw new Error(
      `Sheet "${sheet.name}" has ${hits.length} rows labelled "${label}"; a cross-sheet ` +
        `formula needs exactly one. Rename the duplicate or fix the label.`,
    );
  }
  return hits[0];
}

function totalsSheet(sourceSheets: readonly SheetSpec[]): SheetSpec {
  const years = consolidated();
  const metroIds = years[0].metros.map((m) => m.metroId);
  const sheetFor = (id: string) => SHEET_BY_METRO[id] ?? 'Metros_4toN';
  const specFor = (id: string) => {
    const name = sheetFor(id);
    const found = sourceSheets.find((s) => s.name === name);
    if (!found) throw new Error(`Totals references sheet "${name}", which is not in the workbook.`);
    return found;
  };
  // Looked up by LABEL, never by a remembered row number. Metro sheets and the cohort sheet
  // have different layouts, and both move when a line of explanation is added.
  // The cohort sheet has no subscription/take-rate split to total up, so its revenue row is
  // labelled plainly. A LABEL that differs per sheet is fine and visible in this file; a ROW
  // NUMBER that differs per sheet is the thing that went stale.
  const revenueLabel = (id: string) => (id === COHORT_METRO_ID ? 'Revenue' : 'Total revenue');
  const REVENUE_ROW: Readonly<Record<string, number>> = Object.fromEntries(
    metroIds.map((id) => [id, rowOf(specFor(id), revenueLabel(id))]),
  );
  const EBITDA_ROW: Readonly<Record<string, number>> = Object.fromEntries(
    metroIds.map((id) => [id, rowOf(specFor(id), 'Metro EBITDA')]),
  );
  // Both sheet layouts label this row identically, so unlike revenue it needs no per-sheet
  // variant. Added when the Totals Exit ARR row became live — see the note there.
  const EXIT_ARR_ROW: Readonly<Record<string, number>> = Object.fromEntries(
    metroIds.map((id) => [id, rowOf(specFor(id), 'Exit ARR (year-end run rate)')]),
  );
  // Every reference is sheet-qualified, even ones addressing this same Totals sheet — see
  // formulaEval.ts's header comment for why.
  const tref = (row: number, col: string) => `Totals!${col}${row}`;

  const rows: CellRow[] = [
    [t('Consolidated'), t('Include?'), ...MODEL_YEARS.map((y) => t(String(y)))],
    [blank],
    [t('Revenue by metro')],
  ];

  const firstMetroRow = rows.length + 1;
  const toggleRowByMetro: Record<string, number> = {};
  metroIds.forEach((id) => {
    const toggleRow = rows.length + 1;
    toggleRowByMetro[id] = toggleRow;
    rows.push([
      t(id),
      t('YES'),
      ...MODEL_YEARS.map((_, i) => {
        const value = years[i].metros.find((m) => m.metroId === id)?.revenue ?? 0;
        const source = `${sheetFor(id)}!${SOURCE_COLS[i]}${REVENUE_ROW[id]}`;
        return { v: value, f: `IF(${tref(toggleRow, 'B')}="NO",0,${source})`, fmt: '$#,##0' };
      }),
    ]);
  });

  rows.push([blank]);
  rows.push([
    t('Total revenue (booked in year)'),
    blank,
    ...MODEL_YEARS.map((_, i) => {
      // SUM over an explicit comma-separated list of refs, not a `C4:C6` colon range — the
      // evaluator's tokenizer (deliberately, see formulaEval.ts) has no notion of a range,
      // and a colon range would also be redundant syntax once every ref is sheet-qualified.
      // Numerically identical to a range; just a different, evaluator-checkable spelling.
      const refs = metroIds.map((_id, idx) => tref(firstMetroRow + idx, TOTALS_COLS[i]));
      return { v: years[i].revenue, f: `SUM(${refs.join(',')})`, fmt: '$#,##0' };
    }),
  ]);

  const metroEbitdaRow = rows.length + 1;
  rows.push([
    t('Metro EBITDA'),
    blank,
    ...MODEL_YEARS.map((_, i) => {
      // Correction 2: this must be a live formula too — otherwise changing a metro
      // assumption would flow through to consolidated revenue but not to consolidated
      // EBITDA. One row per metro is not needed (unlike the revenue block above); this
      // single row sums each metro sheet's OWN EBITDA cell, honouring the same toggles.
      const terms = metroIds.map((id) => {
        const source = `${sheetFor(id)}!${SOURCE_COLS[i]}${EBITDA_ROW[id]}`;
        return `IF(${tref(toggleRowByMetro[id], 'B')}="NO",0,${source})`;
      });
      return { v: years[i].metroEbitda, f: `SUM(${terms.join(',')})`, fmt: '$#,##0' };
    }),
  ]);

  // Stays a plain value, deliberately: not a per-metro figure — it comes from the
  // confidential budget at the rollup layer, not from any metro sheet.
  rows.push([t('Shared cost'), blank, ...years.map((y) => n(-y.sharedCost))]);
  const sharedCostRow = rows.length;

  rows.push([
    t('EBITDA'),
    blank,
    ...MODEL_YEARS.map((_, i) => ({
      v: years[i].ebitda,
      f: `${tref(metroEbitdaRow, TOTALS_COLS[i])}+${tref(sharedCostRow, TOTALS_COLS[i])}`,
      fmt: '$#,##0',
    })),
  ]);

  // Stays a plain value, deliberately: the cohort's metro count is not expressible as a
  // cell reference.
  rows.push([t('Metros live'), blank, ...years.map((y) => n(y.metrosLive, '#,##0'))]);

  rows.push(
    [blank],
    [t('Exit ARR — the year-end RUN RATE, not what was booked during the year')],
    // Live and toggled, for the same reason the revenue and EBITDA rows above are. This
    // shipped as a plain value on the argument that a live formula would need ARPU as a cell
    // and ARPU is derived from the tier mix -- true of the METRO sheets, false here, because
    // every metro sheet already prints its own Exit ARR row and this is only their sum.
    // The cost of the plain value was not cosmetic: the README advertises the YES/NO toggles,
    // so a reader switches Manhattan off, watches booked revenue drop by a third, and sees
    // Exit ARR and the cross-check multiple below it refuse to move. A cross-check that
    // silently ignores the control the sheet tells you to use is worse than no cross-check.
    [
      t('Exit ARR'),
      blank,
      ...MODEL_YEARS.map((_, i) => {
        const terms = metroIds.map((id) => {
          const source = `${sheetFor(id)}!${SOURCE_COLS[i]}${EXIT_ARR_ROW[id]}`;
          return `IF(${tref(toggleRowByMetro[id], 'B')}="NO",0,${source})`;
        });
        return { v: years[i].exitArr, f: `SUM(${terms.join(',')})`, fmt: '$#,##0' };
      }),
    ],
  );
  const exitArrRow = rows.length;
  rows.push(
    [t('Booked revenue above is summed month by month while customers are still ramping, so')],
    [t('it sits below the year-end run rate in every growth year. The comparison below needs')],
    [t('the run rate, because the plan it compares against is stated as ARR.')],
    [blank],
    [t('Cross-check — the SUPERSEDED top-down plan (PROJECT_CONTEXT section 3, before 2026-08-26)')],
    [t('Prior plan ARR, low'), blank, ...years.map((y) => n(y.priorPlanArrLow))],
    [t('Prior plan ARR, high'), blank, ...years.map((y) => n(y.priorPlanArrHigh))],
  );
  const lowRow = rows.length - 1;
  const highRow = rows.length;
  rows.push([
    t('Exit ARR as a multiple of the prior plan’s band midpoint'),
    blank,
    ...MODEL_YEARS.map((_, i) => ({
      v: years[i].bottomUpVsPriorPlan,
      // EXIT ARR over the band, never booked revenue over the band. The band is an ARR
      // figure; dividing booked revenue by it compared two different quantities.
      f: `${tref(exitArrRow, TOTALS_COLS[i])}/((${tref(lowRow, TOTALS_COLS[i])}+${tref(highRow, TOTALS_COLS[i])})/2)`,
      fmt: '0.00x',
    })),
  ]);
  rows.push(
    [t('These are expected to disagree, and the gap is reported rather than closed. Section 3')],
    [t('now states this model’s figures; the band above is kept as the plan it replaced, so an')],
    [t('investor who saw the earlier number can be answered. Neither side has been tuned to')],
    [t('meet the other — the band’s six values are unchanged, deliberately, because updating')],
    [t('them to match would make the ratio 1.00x by construction and the cross-check worthless.')],
  );
  return { name: 'Totals', rows };
}

/**
 * The tier-mix blends, the campaign value and the CAC midpoint, as LIVE formulas over the
 * Assumptions sheet's named cells.
 *
 * These are the cells every metro sheet multiplies its customer-months by, so they are what
 * makes editing a tier price or the mix reach revenue. They live here rather than on
 * Assumptions because they are not assumptions: each is computed from four or two cells that
 * are. Putting a blend on the Assumptions sheet would invite a reader to edit it directly and
 * silently decouple it from the mix it is supposed to summarise.
 *
 * Public-safe by construction: every input is in `REGISTER`, which ships on the Assumptions
 * sheet in both builds. Nothing here reads `./confidential`.
 */
function derivedDriverFormulas(): Readonly<Record<keyof typeof UE, string>> {
  const cap = (s: string) => s[0].toUpperCase() + s.slice(1);
  const blend = (rate: (tier: string) => string) =>
    TIERS.map((tier) => `${asmName(`tierMix${cap(tier)}`)}*${rate(tier)}`).join('+');

  // `(low+high)/2*deliverables` — the same order `avgCampaignValue()` computes it in.
  const avgCampaignValueF =
    `(${asmName('campaignPriceStandardLow')}+${asmName('campaignPriceStandardHigh')})/2` +
    `*${asmName('deliverablesPerCampaign')}`;

  return {
    blendedSubscription: blend((tier) => asmName(`price_${tier}`)),
    blendedTakeRate: blend((tier) => asmName(`takeRate_${tier}`)),
    avgCampaignValue: avgCampaignValueF,
    // Reproduces `revenuePerCustomerMonth`, which is documented as the model's single
    // definition of ARPU: one customer's subscription plus the take rate on the campaigns
    // that one customer runs in a month. Written from the other two ue_ cells rather than
    // re-expanded from the mix, so it cannot drift from them.
    arpuPerCustomerMonth:
      `${UE.blendedSubscription}+${asmName('campaignsPerRestaurantPerMonth')}` +
      `*${UE.avgCampaignValue}*${UE.blendedTakeRate}`,
    cac: `(${asmName('restaurantCacLow')}+${asmName('restaurantCacHigh')})/2`,
  };
}

function unitEconomicsSheet(): SheetSpec {
  const u = unitEconomics(REGISTERED_MIX);
  const f = derivedDriverFormulas();
  const driver = (key: keyof typeof UE, v: number, fmt: string): Cell => ({
    v,
    f: f[key],
    name: UE[key],
    fmt,
  });
  return {
    name: 'Unit_Economics',
    rows: [
      [t('Unit economics'), t('Value')],
      [t('Gross profit per business per month'), n(u.grossProfitPerBusinessPerMonth, '$#,##0.00')],
      [t('Customer lifetime (months)'), n(u.customerLifetimeMonths, '#,##0.0')],
      [t('LTV'), n(u.ltv)],
      [t('LTV:CAC at low CAC'), { v: u.ltvToCacAtCacLow, fmt: '0.00x' }],
      [t('LTV:CAC at high CAC'), { v: u.ltvToCacAtCacHigh, fmt: '0.00x' }],
      [t('CAC payback at low CAC (months)'), n(u.cacPaybackMonthsAtCacLow, '#,##0.0')],
      [t('CAC payback at high CAC (months)'), n(u.cacPaybackMonthsAtCacHigh, '#,##0.0')],
      [blank],
      [t('CAC is MODELED, not measured — the source states it as a target and DragonCandy has')],
      [t('never acquired a paying customer. This is a projection measured against a projection.')],
      [blank],
      [t('Derived drivers — what the tier mix is worth')],
      [t('These are NOT assumptions and are not on the Assumptions sheet. Each is computed from')],
      [t('the tier-mix, pricing and cost cells that ARE, and every metro sheet references these')],
      [t('by name — so changing a tier price or the mix moves campaigns, GMV, revenue and cost')],
      [t('on all four metro sheets, the cohort sheet and the Totals rollup.')],
      [t('Blended subscription per customer per month'),
       driver('blendedSubscription', blendedSubscription(REGISTERED_MIX), '$#,##0.00')],
      [t('Blended take rate'), driver('blendedTakeRate', blendedTakeRate(REGISTERED_MIX), '0.00%')],
      [t('Average campaign value'), driver('avgCampaignValue', avgCampaignValue(), '$#,##0.00')],
      [t('Revenue per customer per month (ARPU)'),
       driver('arpuPerCustomerMonth', revenuePerCustomerMonth(REGISTERED_MIX), '$#,##0.00')],
      [t('Blended restaurant CAC (midpoint of the registered band)'),
       driver('cac', blendedCac(), '$#,##0')],
    ],
  };
}

function financingSheet(): SheetSpec {
  const total = budgetTotal(PRE_SEED_BUDGET, PRE_SEED_HORIZON_MONTHS);
  const raise = preSeedRaise();
  const allocation = buildFundsAllocation(raise.raise, USE_OF_FUNDS_SPLIT);
  const rows: CellRow[] = [
    [t('Financing — CONFIDENTIAL'), t('Amount')],
    [blank],
    [t('Pre-seed budget')],
  ];
  for (const line of PRE_SEED_BUDGET) {
    rows.push([
      t(line.label),
      n(line.monthlyCost, '$#,##0'),
      t(`months ${line.startMonth}–${line.endMonth}`),
    ]);
  }
  rows.push(
    [blank],
    [t(`Total over ${PRE_SEED_HORIZON_MONTHS} months`), n(total)],
    [t('Raise'), n(raise.raise)],
    [blank],
    [t('Use of funds')],
  );
  for (const bucket of allocation) {
    rows.push([t(bucket.label), { v: bucket.share, fmt: '0%' }, n(bucket.amount)]);
  }
  rows.push(
    [blank],
    [t('SAFE terms — cap, discount, MFN — are a founder decision, not a derivation, and are')],
    [t('deliberately absent. Launch event budget is blocked on launchEventPlan in deck/pending.ts.')],
  );
  return { name: FINANCING_SHEET, rows };
}

export function buildWorkbookSpec({ confidential }: { confidential: boolean }): readonly SheetSpec[] {
  // The metro and cohort sheets are built FIRST, because `totalsSheet` resolves its
  // cross-sheet formula targets by reading their labels rather than by remembering their
  // row numbers. See `rowOf`.
  const metroSheets = enabledMetros().map((m) => metroSheet(m.id));
  const sourceSheets: SheetSpec[] = [...metroSheets, cohortSheet(metroSheets)];
  const sheets: SheetSpec[] = [
    readmeSheet(),
    { name: 'Assumptions', rows: [
      [t('key'), t('label'), t('value'), t('provenance'), t('source'), t('as of'), t('unit'), t('note')],
      ...assumptionRows(confidential),
    ] },
    sourcesSheet(),
    ...sourceSheets,
    sharedCostsSheet(),
    totalsSheet(sourceSheets),
    unitEconomicsSheet(),
  ];
  if (confidential) sheets.push(financingSheet());
  return sheets;
}
