/**
 * The workbook, as data. `exceljs` never appears here — the writer is a separate script.
 *
 * Keeping the sheet contents as plain cells means a test can walk every cell and assert
 * that no number arrived without provenance (see workbookProvenance.test.ts), which is the
 * control that turns "no made-up numbers" from a promise into a failing build.
 */
import { REGISTER } from './assumptions';
import {
  METRO_ASSUMPTIONS,
  METROS,
  MODEL_YEARS,
  addressableVenues,
  totalFoodServiceVenues,
  ADDRESSABLE_NAICS,
  ADDRESSABLE_BUCKETS,
  enabledMetros,
} from './metros';
import { loadCensusSnapshot, snapshotFor } from './censusTam';
import { projectMetroYear, metroKpis } from './metroModel';
import { rollup, COHORT_METRO_COUNTS, sharedCostForYear } from './rollup';
import { REGISTERED_MIX } from './project';
import { unitEconomics } from './derive';
import {
  PRE_SEED_BUDGET,
  PRE_SEED_HORIZON_MONTHS,
  budgetTotal,
  preSeedRaise,
  buildFundsAllocation,
  USE_OF_FUNDS_SPLIT,
  CONFIDENTIAL_ASSUMPTIONS,
} from './confidential';
import type { Assumption } from './types';

export interface Cell {
  readonly v: string | number | null;
  /** Excel formula, without the leading `=`. Task 7 fills these in. */
  readonly f?: string;
  /** Defined name for this cell, so formulas elsewhere can reference it by name. */
  readonly name?: string;
  /** Excel number format, e.g. `'$#,##0'` or `'0.0%'`. */
  readonly fmt?: string;
}

export type CellRow = readonly Cell[];

export interface SheetSpec {
  readonly name: string;
  readonly rows: readonly CellRow[];
}

export const FINANCING_SHEET = 'Financing';

export const SHEET_ORDER = [
  'README',
  'Assumptions',
  'Sources',
  'Hoboken_Model',
  'Manhattan_Model',
  'PalmBeach_Model',
  'Metros_4toN',
  'Shared_Costs',
  'Totals',
  'Unit_Economics',
  FINANCING_SHEET,
] as const;

const t = (v: string): Cell => ({ v });
const n = (v: number, fmt = '$#,##0'): Cell => ({ v, fmt });
const pct = (v: number): Cell => ({ v, fmt: '0.0%' });
const blank: Cell = { v: null };

const SHEET_BY_METRO: Readonly<Record<string, string>> = {
  hoboken: 'Hoboken_Model',
  manhattan: 'Manhattan_Model',
  'palm-beach': 'PalmBeach_Model',
};

/**
 * `confidentialAssumptions` is included only for the confidential build. The Assumptions sheet
 * ships in BOTH builds, so putting founder salaries / use-of-funds shares here unconditionally
 * would leak them into the public workbook the same way `FINANCING_SHEET` is gated instead.
 */
function assumptionRows(confidential: boolean): CellRow[] {
  const all: Array<[string, Assumption<number>]> = [
    ...Object.entries(REGISTER),
    ...Object.entries(METRO_ASSUMPTIONS),
    ...MODEL_YEARS.map((y) => [`cohortMetros_${y}`, COHORT_METRO_COUNTS[y]] as [string, Assumption<number>]),
    ...(confidential ? Object.entries(CONFIDENTIAL_ASSUMPTIONS) : []),
  ];
  return all.map(([key, a]) => [
    t(key),
    t(a.label),
    { v: a.value, name: `asm_${key}` },
    t(a.provenance),
    t(a.source),
    t(a.provenance === 'MEASURED' ? a.asOf : ''),
    t(a.unit),
    t(a.note ?? ''),
  ]);
}

function readmeSheet(): SheetSpec {
  return {
    name: 'README',
    rows: [
      [t('DragonCandy — three-year financial model')],
      [t('Generated by `npm run model:xlsx`. Do not edit by hand; the next run overwrites it.')],
      [blank],
      [t('Every input lives on the Assumptions sheet as a named cell. Change one and the')],
      [t('metro sheets, the Totals rollup and every ratio reflow. Nothing else holds a raw number.')],
      [blank],
      [t('Provenance: MEASURED = read off production, an invoice or the codebase on the stated')],
      [t('date, with the command that re-reads it. BENCHMARKED = an external comparable, with a')],
      [t('URL. MODELED = ours, with the driver named. See the Assumptions and Sources sheets.')],
      [blank],
      [t('Toggle a metro in or out with the YES/NO cells on Totals.')],
    ],
  };
}

function sourcesSheet(): SheetSpec {
  const snap = loadCensusSnapshot();
  const rows: CellRow[] = [
    [t('Sources')],
    [blank],
    [t('Market size — US Census Business Patterns')],
    [t('NAICS in the addressable band'), t(ADDRESSABLE_NAICS.join(', '))],
    [t('Employment-size buckets'), t(ADDRESSABLE_BUCKETS.join(', '))],
    [t('Excluded: 722513 limited-service'), t('franchised fast food — social is set at corporate, not by the location')],
    [t('Excluded: 7223 special food services'), t('catering and food trucks — no fixed venue to market')],
    [t('Excluded: under 5 employees'), t('below the $149 entry tier’s plausible budget')],
    [t('Excluded: 50+ employees'), t('has, or is owned by someone who has, a marketing function')],
    [blank],
  ];
  for (const m of snap.metros) {
    rows.push([t(m.metroId), t(m.geography.label), t(`vintage ${m.vintage}`), t(m.sourceUrl), t(`fetched ${m.fetchedAt}`)]);
  }
  rows.push(
    [blank],
    [t('Census suppression')],
    [t('Cells marked "N" are suppressed to protect respondent confidentiality. They are treated')],
    [t('as unknown, never as zero. A bucket forced by the establishment total is recovered as')],
    [t('the residual; where more than one is suppressed the model states a range.')],
    [blank],
    [t('Rows in Adrian’s model that are OMITTED here, deliberately')],
    [t('Bonus costs'), t('no analogue — DragonCandy discounts nothing')],
    [t('Statutory gaming tax'), t('no analogue — not a gaming business')],
    [t('Market access fees'), t('no analogue — no licence holder takes a share')],
    [t('A row shaped like his but filled with an invented number would be worse than its absence.')],
    [blank],
    [t('Every other number traces to the Assumptions sheet, which carries its provenance and source.')],
  );
  return { name: 'Sources', rows };
}

function metroSheet(metroId: string): SheetSpec {
  const snap = snapshotFor(loadCensusSnapshot(), metroId);
  const years = MODEL_YEARS.map((y) => projectMetroYear(metroId, y, REGISTERED_MIX));
  const label = METROS.find((m) => m.id === metroId)!.label;

  const line = (name: string, pick: (y: (typeof years)[number]) => number, fmt?: string): CellRow => [
    t(name),
    ...years.map((y) => (fmt === '0.0%' ? pct(pick(y)) : n(pick(y), fmt))),
  ];

  return {
    name: SHEET_BY_METRO[metroId],
    rows: [
      [t(label), ...MODEL_YEARS.map((y) => t(String(y)))],
      [t(`${snap.geography.label} — Census ${snap.vintage}`)],
      [blank],
      [t('Market')],
      [t('Total food service venues'), ...years.map(() => n(totalFoodServiceVenues(metroId), '#,##0'))],
      [t('Addressable venues'), ...years.map(() => n(addressableVenues(metroId), '#,##0'))],
      line('Penetration of addressable', (y) => y.penetrationAtYearEnd, '0.0%'),
      line('Customers at year end', (y) => y.customersAtYearEnd, '#,##0'),
      line('Gross adds (incl. churn replacement)', (y) => y.grossAdds, '#,##0'),
      [blank],
      [t('Revenue')],
      line('Campaigns', (y) => y.campaigns, '#,##0'),
      line('GMV', (y) => y.gmv),
      line('Subscription revenue', (y) => y.subscriptionRevenue),
      line('Take-rate revenue', (y) => y.takeRateRevenue),
      line('Total revenue', (y) => y.revenue),
      [blank],
      [t('Cost of revenue')],
      line('Stripe fees', (y) => -y.stripeCost),
      line('AI and infrastructure', (y) => -y.serveCost),
      line('Total cost of revenue', (y) => -y.costOfRevenue),
      line('Gross profit', (y) => y.grossProfit),
      [blank],
      [t('Marketing')],
      line('Acquisition marketing', (y) => -y.marketingCost),
      [blank],
      [t('Metro EBITDA'), ...years.map((y) => n(y.metroEbitda))],
      [blank],
      [t('KPIs')],
      line('Gross margin', (y) => metroKpis(y).grossMarginPct, '0.0%'),
      line('Marketing as % of revenue', (y) => metroKpis(y).marketingPctOfRevenue, '0.0%'),
      line('Cost of revenue as % of revenue', (y) => metroKpis(y).costOfRevenuePctOfRevenue, '0.0%'),
    ],
  };
}

function cohortSheet(): SheetSpec {
  const years = rollup().map((r) => r.metros.find((m) => m.metroId === 'cohort')!);
  return {
    name: 'Metros_4toN',
    rows: [
      [t('Metros beyond the three named'), ...MODEL_YEARS.map((y) => t(String(y)))],
      [t('These metros have not been chosen. Modeled as N copies of an average metro rather')],
      [t('than as invented named cities. Change the count on the Assumptions sheet.')],
      [blank],
      [t('Metros in cohort'), ...MODEL_YEARS.map((y) => n(COHORT_METRO_COUNTS[y].value, '#,##0'))],
      [t('Customers at year end'), ...years.map((y) => n(y.customersAtYearEnd, '#,##0'))],
      [t('Revenue'), ...years.map((y) => n(y.revenue))],
      [t('Gross profit'), ...years.map((y) => n(y.grossProfit))],
      [t('Marketing'), ...years.map((y) => n(-y.marketingCost))],
      [t('Metro EBITDA'), ...years.map((y) => n(y.metroEbitda))],
    ],
  };
}

function sharedCostsSheet(): SheetSpec {
  const years = rollup();
  const rows: CellRow[] = [
    [t('Shared costs'), ...MODEL_YEARS.map((y) => t(String(y)))],
    [t('Payroll, AI and shared infrastructure, allocated across metros by revenue share.')],
    [t('Before any metro has revenue the split is even — a revenue-weighted split of zero')],
    [t('is a division by zero, not an allocation.')],
    [blank],
    [t('Total shared cost'), ...MODEL_YEARS.map((y) => n(sharedCostForYear(y)))],
    [blank],
    [t('Allocation')],
  ];
  const metroIds = years[0].allocations.map((a) => a.metroId);
  for (const id of metroIds) {
    rows.push([
      t(id),
      ...years.map((y) => n(y.allocations.find((a) => a.metroId === id)?.amount ?? 0)),
    ]);
  }
  return { name: 'Shared_Costs', rows };
}

function totalsSheet(): SheetSpec {
  const years = rollup();
  const metroIds = years[0].metros.map((m) => m.metroId);
  const rows: CellRow[] = [
    [t('Consolidated'), t('Include?'), ...MODEL_YEARS.map((y) => t(String(y)))],
    [blank],
    [t('Revenue by metro')],
  ];
  for (const id of metroIds) {
    rows.push([
      t(id),
      t('YES'),
      ...years.map((y) => n(y.metros.find((m) => m.metroId === id)?.revenue ?? 0)),
    ]);
  }
  rows.push(
    [blank],
    [t('Total revenue'), blank, ...years.map((y) => n(y.revenue))],
    [t('Metro EBITDA'), blank, ...years.map((y) => n(y.metroEbitda))],
    [t('Shared cost'), blank, ...years.map((y) => n(-y.sharedCost))],
    [t('EBITDA'), blank, ...years.map((y) => n(y.ebitda))],
    [t('Metros live'), blank, ...years.map((y) => n(y.metrosLive, '#,##0'))],
    [blank],
    [t('Cross-check — PROJECT_CONTEXT section 3 top-down band')],
    [t('Top-down revenue, low'), blank, ...years.map((y) => n(y.topDownRevenueLow))],
    [t('Top-down revenue, high'), blank, ...years.map((y) => n(y.topDownRevenueHigh))],
    [t('Bottom-up as a multiple of the band midpoint'), blank, ...years.map((y) => ({ v: y.bottomUpVsTopDown, fmt: '0.00x' }))],
    [t('These are expected to disagree. The band was asserted top-down; this model is built')],
    [t('bottom-up from Census venue counts. Neither has been tuned to match the other.')],
  );
  return { name: 'Totals', rows };
}

function unitEconomicsSheet(): SheetSpec {
  const u = unitEconomics(REGISTERED_MIX);
  return {
    name: 'Unit_Economics',
    rows: [
      [t('Unit economics'), t('Value')],
      [t('Gross profit per business per month'), n(u.grossProfitPerBusinessPerMonth, '$#,##0.00')],
      [t('Customer lifetime (months)'), n(u.customerLifetimeMonths, '#,##0.0')],
      [t('LTV'), n(u.ltv)],
      [t('LTV:CAC at low CAC'), { v: u.ltvToCacAtCacLow, fmt: '0.00x' }],
      [t('LTV:CAC at high CAC'), { v: u.ltvToCacAtCacHigh, fmt: '0.00x' }],
      [t('CAC payback at low CAC (months)'), n(u.cacPaybackMonthsAtCacLow, '#,##0.0')],
      [t('CAC payback at high CAC (months)'), n(u.cacPaybackMonthsAtCacHigh, '#,##0.0')],
      [blank],
      [t('CAC is MODELED, not measured — the source states it as a target and DragonCandy has')],
      [t('never acquired a paying customer. This is a projection measured against a projection.')],
    ],
  };
}

function financingSheet(): SheetSpec {
  const total = budgetTotal(PRE_SEED_BUDGET, PRE_SEED_HORIZON_MONTHS);
  const raise = preSeedRaise();
  const allocation = buildFundsAllocation(raise.raise, USE_OF_FUNDS_SPLIT);
  const rows: CellRow[] = [
    [t('Financing — CONFIDENTIAL'), t('Amount')],
    [blank],
    [t('Pre-seed budget')],
  ];
  for (const line of PRE_SEED_BUDGET) {
    rows.push([
      t(line.label),
      n(line.monthlyCost, '$#,##0'),
      t(`months ${line.startMonth}–${line.endMonth}`),
    ]);
  }
  rows.push(
    [blank],
    [t(`Total over ${PRE_SEED_HORIZON_MONTHS} months`), n(total)],
    [t('Raise'), n(raise.raise)],
    [blank],
    [t('Use of funds')],
  );
  for (const bucket of allocation) {
    rows.push([t(bucket.label), { v: bucket.share, fmt: '0%' }, n(bucket.amount)]);
  }
  rows.push(
    [blank],
    [t('SAFE terms — cap, discount, MFN — are a founder decision, not a derivation, and are')],
    [t('deliberately absent. Launch event budget is blocked on launchEventPlan in deck/pending.ts.')],
  );
  return { name: FINANCING_SHEET, rows };
}

export function buildWorkbookSpec({ confidential }: { confidential: boolean }): readonly SheetSpec[] {
  const sheets: SheetSpec[] = [
    readmeSheet(),
    { name: 'Assumptions', rows: [
      [t('key'), t('label'), t('value'), t('provenance'), t('source'), t('as of'), t('unit'), t('note')],
      ...assumptionRows(confidential),
    ] },
    sourcesSheet(),
    ...enabledMetros().map((m) => metroSheet(m.id)),
    cohortSheet(),
    sharedCostsSheet(),
    totalsSheet(),
    unitEconomicsSheet(),
  ];
  if (confidential) sheets.push(financingSheet());
  return sheets;
}
