/**
 * Deciding whether a Supabase URL points at the production project.
 *
 * Lives here, separate from `client.ts`, for two reasons: `client.ts` creates the
 * client as an import side effect (so it is awkward to unit-test), and `client.ts`
 * still carries a "this file is automatically generated" header from the Lovable era.
 * Keeping the rule in a plain, tested module means the decision itself is covered even
 * if that file is ever regenerated.
 *
 * The rule compares HOSTS, never whole strings. A trailing slash, different casing, or
 * an added path all describe the same project while failing an equality check — so a
 * string comparison fails OPEN, which is the worst way for a safety control to be wrong.
 */

/** The production Supabase project's host. The one place this ref belongs in `src/`. */
export const PROD_SUPABASE_HOST = 'zocahiffooqdybdhguqv.supabase.co';

/** The staging project — what local development should use. */
export const STAGING_SUPABASE_HOST = 'mhffqrawgizhprbobcta.supabase.co';

export type SupabaseTarget =
  /** Definitely the production project. */
  | 'production'
  /** Some other project (staging, a branch database, a local stack). */
  | 'other'
  /** Not a parseable URL — we cannot prove it is safe. */
  | 'unparseable';

/**
 * Classify a Supabase URL.
 *
 * Anything we cannot parse is reported as `unparseable` rather than assumed safe, so
 * callers can fail closed.
 */
export function classifySupabaseUrl(url: string | undefined | null): SupabaseTarget {
  if (!url) return 'unparseable';
  let host: string;
  try {
    host = new URL(url).hostname.toLowerCase();
  } catch {
    return 'unparseable';
  }
  return host === PROD_SUPABASE_HOST ? 'production' : 'other';
}

/** True when this URL resolves to the production project, in any spelling. */
export function isProductionSupabaseUrl(url: string | undefined | null): boolean {
  return classifySupabaseUrl(url) === 'production';
}
