project_id = "zocahiffooqdybdhguqv"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false
