/**
 * Write the speaker notes to `.pitch-notes.json` for the PDF exporter to read.
 *
 * The exporter is plain Node and cannot import a `.ts` module; this bridges the two
 * without putting the notes into the shipped bundle. That matters: the notes are candid
 * coaching ("do not inflate — an investor checks"), and they have no business inside a
 * JavaScript file a stranger can fetch from the live site.
 *
 * Gitignored. Regenerated by `npm run pitch:pdf` every time.
 */
import { writeFileSync } from 'node:fs';

import { NOTES } from '../src/pitch/slides/notes';
import { OUTSTANDING, outstandingReport } from '../src/pitch/deck/pending';

const OUT = '.pitch-notes.json';

// The order lives in src/pitch/slides/index.ts, which imports React and therefore cannot
// be imported here. Object key order in NOTES is the deck order and is asserted to match
// by `notes.test.ts`, so a divergence fails a test rather than silently mis-pairing a
// note with the wrong slide.
const slides = Object.entries(NOTES).map(([id, note]) => ({
  id,
  title: note.title,
  notes: note.notes,
}));

writeFileSync(
  OUT,
  JSON.stringify(
    {
      slides,
      outstanding: OUTSTANDING.map((i) => ({ key: i.key, question: i.question, blocks: i.blocks })),
      outstandingReport: outstandingReport(),
    },
    null,
    2,
  ),
);

console.log(`Wrote ${OUT} (${slides.length} slides, ${OUTSTANDING.length} outstanding inputs)`);
