/**
 * Generate `docs/DragonCandy_Investor_QA.md` — the one-page cheat sheet from spec §7.
 *
 *   npm run pitch:qa
 *
 * Every number in the deck, where it came from, and the honest answer to *"how do you
 * know that?"* — so Joe can answer without calling Damon.
 *
 * Generated, not written. A hand-maintained cheat sheet is a second copy of the register
 * that goes stale in exactly the way this whole model exists to prevent, and it would go
 * stale silently because nothing reads it until someone is in a meeting.
 *
 * Public-safe by construction: it imports the register and the derivations, never
 * `confidential.ts`. The raise, the budget and the runway are not here.
 */
import { writeFileSync } from 'node:fs';

import { MARKET, OPERATING, PRICING, TIER_TAKE_RATES, UNIT_ECONOMICS, REGISTER } from '../src/pitch/model/assumptions';
import { MAX_MEASURED_AGE_DAYS, findStale, type Assumption } from '../src/pitch/model/types';
import { REGISTERED_MIX, avgCampaignValue, projectMonth } from '../src/pitch/model/project';
import {
  LIQUIDITY_THRESHOLD,
  businessStepTable,
  isLiquid,
  monthsToLiquidity,
  threeYearTrajectory,
  unitEconomics,
} from '../src/pitch/model/derive';
import { count, money, moneyShort, pct } from '../src/pitch/deck/format';
import { GLOSSARY } from '../src/pitch/deck/glossary';
import { FOUNDER_FACTS, OUTSTANDING } from '../src/pitch/deck/pending';

const OUT = 'docs/DragonCandy_Investor_QA.md';

// Same refusal as the model document: a cheat sheet built from stale inputs is worse
// than none, because it is carried into the room and believed.
const stale = findStale(REGISTER, new Date(), MAX_MEASURED_AGE_DAYS);
if (stale.length > 0) {
  console.error(`Refusing to generate: ${stale.length} measured input(s) are stale.`);
  for (const s of stale) console.error(`  · ${s.key} (asOf ${s.asOf})`);
  process.exit(1);
}

const at100 = projectMonth({ month: 0, restaurants: 100, mix: REGISTERED_MIX });
const one = projectMonth({ month: 0, restaurants: 1, mix: REGISTERED_MIX });
const u = unitEconomics(REGISTERED_MIX);
const steps = businessStepTable([100, 1000, 10000], REGISTERED_MIX);
const years = threeYearTrajectory();
const ratio = MARKET.creatorsPerRestaurant.value;
const liquidMonth = monthsToLiquidity({
  restaurantsPerMonth: 2,
  creatorsPerMonth: 2 * ratio,
  horizonMonths: 36,
});
const starvedMonth = monthsToLiquidity({
  restaurantsPerMonth: 2,
  creatorsPerMonth: 2 * 2,
  horizonMonths: 36,
});

const L: string[] = [];
const p = (s = '') => L.push(s);

/**
 * A cell's contents must not contain a bare `|`.
 *
 * Half the sources here are shell pipelines — `find src/pages -name '*.tsx' | wc -l` —
 * and a pipe splits the cell, so the row silently grows extra columns and renders as
 * garbage. A code span does NOT protect it: GFM still treats `|` as a delimiter inside
 * backticks, and it must be backslash-escaped. `scripts/generate-investor-model.ts` hit
 * this same thing (commit d0330123) and this file reproduced it.
 */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

function row(a: Assumption<number>, shown: string) {
  const asOf = 'asOf' in a && a.asOf ? `, read ${a.asOf}` : '';
  return `| ${cell(a.label)} | ${shown} | \`${a.provenance}\` | ${cell(a.source)}${asOf} |`;
}

p('# DragonCandy — Investor Q&A');
p();
p('> **Generated by `npm run pitch:qa` from `src/pitch/model/`. Do not edit by hand —');
p('> your edits will be overwritten, and the numbers here are supposed to be the same');
p('> ones the deck renders.**');
p();
p('Every figure in the deck, where it came from, and what to say when someone asks how');
p('you know. Public-safe: the pre-seed budget, the raise and the runway are deliberately');
p('not in this file.');
p();

p('## The one thing to say before any number');
p();
p('DragonCandy has **zero paying customers** and Stripe is in test mode. Prices and the');
p('built platform are real and measured; the volumes they are multiplied by are modelled.');
p('Every table below says which is which, and saying it first is stronger than being');
p('asked.');
p();
p('**"So how many restaurants do you actually have?"** — ' + FOUNDER_FACTS.launchRestaurants.statement);
p(`That is a different number from the **${count(OPERATING.registeredUsers.value)} registered accounts** and from the`);
p('**' + count(OPERATING.payingCustomers.value) + ' paying customers**, and the three must not be substituted for each other in the');
p(`room. Source: ${FOUNDER_FACTS.launchRestaurants.source}, ${FOUNDER_FACTS.launchRestaurants.asOf} — a founder`);
p('statement, which is why it is not in the assumptions register and carries no provenance tag.');
p();

p('## Slide 6 — what is actually built');
p();
p('| Figure | In the deck | Provenance | How we know |');
p('|---|---|---|---|');
for (const a of [
  OPERATING.pageComponents,
  OPERATING.hooks,
  OPERATING.edgeFunctions,
  OPERATING.migrations,
  OPERATING.sourceFiles,
  OPERATING.tests,
  OPERATING.testFiles,
  OPERATING.burnMonthly,
]) {
  p(row(a, a.unit === 'USD/month' ? money(a.value) : count(a.value)));
}
p();
p('**"How do you know?"** — each of those is a shell command in the register, re-runnable');
p('in about a second. Offer to run one.');
p();

p('## Slide 8 — how the money works');
p();
p('| Figure | In the deck | Provenance | How we know |');
p('|---|---|---|---|');
for (const tier of ['starter', 'growth', 'pro'] as const) {
  p(row(PRICING[tier], money(PRICING[tier].value)));
}
for (const tier of ['free', 'pro'] as const) {
  p(row(TIER_TAKE_RATES[tier], pct(TIER_TAKE_RATES[tier].value * 100)));
}
p(row(MARKET.campaignsPerRestaurantPerMonth, String(MARKET.campaignsPerRestaurantPerMonth.value)));
p(row(MARKET.deliverablesPerCampaign, String(MARKET.deliverablesPerCampaign.value)));
p();
p(`Average campaign value **${money(avgCampaignValue())}** — the midpoint of the app's own`);
p(`standard band (${money(MARKET.campaignPriceStandardLow.value)}–${money(MARKET.campaignPriceStandardHigh.value)} a deliverable) times ${MARKET.deliverablesPerCampaign.value} deliverables.`);
p();
p(`At 100 restaurants: **${money(at100.totalRevenue)}/month** — ${money(at100.subscriptionRevenue)} subscription plus ${money(at100.takeRateRevenue)} take rate, on ${count(at100.campaigns)} campaigns worth ${money(at100.gmvDollars)}.`);
p();
p('**"Are the other two streams real?"** — AI overages and the DragonDash rush surcharge');
p('are live in the product and have never been charged, so they are valued at **$0** in');
p('every figure in the deck. Say that before being asked; it makes the two we do count');
p('easier to believe.');
p();

p('## Slide 9 — unit economics');
p();
p('| Figure | In the deck | Provenance | How we know |');
p('|---|---|---|---|');
p(row(UNIT_ECONOMICS.restaurantCacLow, money(UNIT_ECONOMICS.restaurantCacLow.value)));
p(row(UNIT_ECONOMICS.restaurantCacHigh, money(UNIT_ECONOMICS.restaurantCacHigh.value)));
p(row(UNIT_ECONOMICS.monthlyChurn, pct(UNIT_ECONOMICS.monthlyChurn.value * 100, 1)));
p();
p(`Gross profit per restaurant per month **${money(u.grossProfitPerBusinessPerMonth)}** (${pct(one.grossMarginPct, 1)} gross margin) · lifetime **${u.customerLifetimeMonths.toFixed(0)} months** · LTV **${money(u.ltv)}** · LTV:CAC **${u.ltvToCacAtCacHigh.toFixed(1)}–${u.ltvToCacAtCacLow.toFixed(1)}:1** · payback **${u.cacPaybackMonthsAtCacLow.toFixed(1)}–${u.cacPaybackMonthsAtCacHigh.toFixed(1)} months**.`);
p();
p('**"How do you know your CAC?"** — *We do not.* We have never acquired a paying');
p('customer. That band is a target from our own pricing work, so the ratio is honest');
p('arithmetic on two assumptions, not a measurement. What is solid is the cost side:');
p(`serving one more restaurant costs about ${money(UNIT_ECONOMICS.aiCostPerCustomerMonth.value + UNIT_ECONOMICS.infraCostPerCustomerMonth.value)} a month, which is why the margin holds at any scale.`);
p();

p('## Slide 10 — Hoboken liquidity');
p();
p(`Liquid means **≥ ${LIQUIDITY_THRESHOLD.minApplicantsPerCampaign} applicants per campaign** over the ${MARKET.campaignOpenDays.value} days it stays open, **and ≥ ${LIQUIDITY_THRESHOLD.minCampaignsVisibleToCreator} campaigns open** for a creator to choose from.`);
p();
p(`At 2 restaurants and ${2 * ratio} creators a month: **${liquidMonth === null ? 'never within 36 months' : `month ${liquidMonth}`}**.`);
p(`At 2 restaurants and only 4 creators a month: **${starvedMonth === null ? 'never liquid, at any restaurant count' : `month ${starvedMonth}`}**.`);
p();
p(`**"What if you are wrong?"** — the honest weak point: at the target ratio we clear the applicant threshold by ${(((isLiquid(1, ratio).applicantsPerCampaign - LIQUIDITY_THRESHOLD.minApplicantsPerCampaign) / isLiquid(1, ratio).applicantsPerCampaign) * 100).toFixed(0)}% — ${isLiquid(1, ratio).applicantsPerCampaign.toFixed(1)} against a floor of ${LIQUIDITY_THRESHOLD.minApplicantsPerCampaign.toFixed(1)} — and both inputs are modelled. Volunteer that. The defensible part is that the model can express a creator shortage at all, which is the failure mode that actually kills local marketplaces.`);
p();

p('## Slide 11 — 100 / 1,000 / 10,000 businesses');
p();
p('| Businesses | Creators | Campaign volume/mo | Revenue/mo | Revenue/yr | Gross margin |');
p('|---:|---:|---:|---:|---:|---:|');
for (const s of steps) {
  p(
    `| ${count(s.businesses)} | ${count(s.creators)} | ${moneyShort(s.monthlyGmv)} | ${moneyShort(s.monthlyRevenue)} | ${moneyShort(s.annualRevenue)} | ${pct(s.grossMarginPct, 1)} |`,
  );
}
p();
p(`Tier mix assumed: ${pct(MARKET.tierMixFree.value * 100)} free / ${pct(MARKET.tierMixStarter.value * 100)} starter / ${pct(MARKET.tierMixGrowth.value * 100)} growth / ${pct(MARKET.tierMixPro.value * 100)} pro — i.e. ${pct((1 - MARKET.tierMixFree.value) * 100)} of restaurants on a paid plan, from a base of zero today. \`MODELED\`, and it drives most of the revenue above.`);
p();
p(`**"Is churn in these numbers?"** — **No.** Churn is benchmarked at ${pct(UNIT_ECONOMICS.monthlyChurn.value * 100, 1)} a month and no formula applies a drag. This is what the business looks like holding that customer count, not a forecast net of leavers. Say so unprompted.`);
p();

p('## Slide 12 — the trajectory');
p();
p('| Year | Revenue | Total cost | EBITDA |');
p('|---|---|---|---|');
for (const y of years) {
  p(
    `| Y${y.year} | ${moneyShort(y.revenueLow)}–${moneyShort(y.revenueHigh)} | ${moneyShort(y.totalCostLow)}–${moneyShort(y.totalCostHigh)} | ${moneyShort(y.ebitdaLow)} to ${moneyShort(y.ebitdaHigh)} |`,
  );
}
p();
p('Cost is all-in — Stripe, AI, infrastructure, payroll, marketing, legal — so it is not');
p('comparable to the gross-margin figure on slide 9, which excludes everything below the');
p('gross-profit line. The low EBITDA pairs low revenue with **high** cost, which is not');
p('how most decks draw a downside. Point that out.');
p();

p('## Slide 13 — the fine-tune claim');
p();
p('**"Why is 1,000–5,000 the magic number?"** It is the right challenge, and the answer is');
p('that the number was defensible but the **unit** was wrong. A campaign is not one');
p('training example: it is a chain that yields a brief (intent), several applicants');
p('resolving to one hire (a preference pair), an approve-or-reject (a quality label) and a');
p('performance record (an outcome). A few thousand campaigns therefore produce tens of');
p('thousands of labelled preference pairs, which is the regime LoRA is sample-efficient');
p('in, at $50–300 a run. Nothing has been fine-tuned yet.');
p();

p('## Glossary — say the plain version first');
p();
p('| Term | Say this |');
p('|---|---|');
for (const g of GLOSSARY) p(`| ${cell(g.term)} | ${cell(g.gloss)} |`);
p();

if (OUTSTANDING.length > 0) {
  p('## Still outstanding — do not improvise these');
  p();
  p('The deck marks each of these on its slide. If asked, the honest answer is "not');
  p('settled yet", not a number invented in the room.');
  p();
  for (const i of OUTSTANDING) p(`- **${i.blocks}** — ${i.question}`);
  p();
}

writeFileSync(OUT, `${L.join('\n')}\n`);
console.log(`Wrote ${OUT} (${L.length} lines, ${OUTSTANDING.length} outstanding inputs flagged)`);
