/**
 * Generate `docs/DragonCandy_Investor_QA.md` — the one-page cheat sheet from spec §7.
 *
 *   npm run pitch:qa
 *
 * Every number in the deck, where it came from, and the honest answer to *"how do you
 * know that?"* — so Joe can answer without calling Damon.
 *
 * Generated, not written. A hand-maintained cheat sheet is a second copy of the register
 * that goes stale in exactly the way this whole model exists to prevent, and it would go
 * stale silently because nothing reads it until someone is in a meeting.
 *
 * Public-safe by construction: it imports the register and the derivations, never
 * `confidential.ts`. The raise, the budget and the runway are not here.
 */
import { writeFileSync } from 'node:fs';

import { MARKET, OPERATING, PRICING, TIER_TAKE_RATES, UNIT_ECONOMICS, REGISTER } from '../src/pitch/model/assumptions';
import { MAX_MEASURED_AGE_DAYS, findStale, type Assumption } from '../src/pitch/model/types';
import { REGISTERED_MIX, avgCampaignValue, projectMonth } from '../src/pitch/model/project';
import {
  LIQUIDITY_THRESHOLD,
  businessStepTable,
  isLiquid,
  monthsToLiquidity,
  threeYearTrajectory,
  unitEconomics,
} from '../src/pitch/model/derive';
import { rollup } from '../src/pitch/model/rollup';
import { count, money, moneyShort, pct } from '../src/pitch/deck/format';
import { GLOSSARY } from '../src/pitch/deck/glossary';
import { FOUNDER_FACTS, OUTSTANDING } from '../src/pitch/deck/pending';

const OUT = 'docs/DragonCandy_Investor_QA.md';

// Same refusal as the model document: a cheat sheet built from stale inputs is worse
// than none, because it is carried into the room and believed.
const stale = findStale(REGISTER, new Date(), MAX_MEASURED_AGE_DAYS);
if (stale.length > 0) {
  console.error(`Refusing to generate: ${stale.length} measured input(s) are stale.`);
  for (const s of stale) console.error(`  · ${s.key} (asOf ${s.asOf})`);
  process.exit(1);
}

const at100 = projectMonth({ month: 0, restaurants: 100, mix: REGISTERED_MIX });
const one = projectMonth({ month: 0, restaurants: 1, mix: REGISTERED_MIX });
const u = unitEconomics(REGISTERED_MIX);
const steps = businessStepTable([100, 1000, 10000], REGISTERED_MIX);
const years = threeYearTrajectory();
const ratio = MARKET.creatorsPerRestaurant.value;
const liquidMonth = monthsToLiquidity({
  restaurantsPerMonth: 2,
  creatorsPerMonth: 2 * ratio,
  horizonMonths: 36,
});
const starvedMonth = monthsToLiquidity({
  restaurantsPerMonth: 2,
  creatorsPerMonth: 2 * 2,
  horizonMonths: 36,
});

const L: string[] = [];
const p = (s = '') => L.push(s);

/**
 * A cell's contents must not contain a bare `|`.
 *
 * Half the sources here are shell pipelines — `find src/pages -name '*.tsx' | wc -l` —
 * and a pipe splits the cell, so the row silently grows extra columns and renders as
 * garbage. A code span does NOT protect it: GFM still treats `|` as a delimiter inside
 * backticks, and it must be backslash-escaped. `scripts/generate-investor-model.ts` hit
 * this same thing (commit d0330123) and this file reproduced it.
 */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

function row(a: Assumption<number>, shown: string) {
  const asOf = 'asOf' in a && a.asOf ? `, read ${a.asOf}` : '';
  return `| ${cell(a.label)} | ${shown} | \`${a.provenance}\` | ${cell(a.source)}${asOf} |`;
}

p('# DragonCandy — Investor Q&A');
p();
p('> **Generated by `npm run pitch:qa` from `src/pitch/model/`. Do not edit by hand —');
p('> your edits will be overwritten, and the numbers here are supposed to be the same');
p('> ones the deck renders.**');
p();
p('Every figure in the deck, where it came from, and what to say when someone asks how');
p('you know. Public-safe: the pre-seed budget, the raise and the runway are deliberately');
p('not in this file.');
p();

p('## The one thing to say before any number');
p();
p('DragonCandy has **zero paying customers** and Stripe is in test mode. Prices and the');
p('built platform are real and measured; the volumes they are multiplied by are modelled.');
p('Every table below says which is which, and saying it first is stronger than being');
p('asked.');
p();
p('**"So how many restaurants do you actually have?"** — ' + FOUNDER_FACTS.launchRestaurants.statement);
p(`That is a different number from the **${count(OPERATING.registeredUsers.value)} registered accounts** and from the`);
p('**' + count(OPERATING.payingCustomers.value) + ' paying customers**, and the three must not be substituted for each other in the');
p(`room. Source: ${FOUNDER_FACTS.launchRestaurants.source}, ${FOUNDER_FACTS.launchRestaurants.asOf} — a founder`);
p('statement, which is why it is not in the assumptions register and carries no provenance tag.');
p();

p('## Slide 6 — what is actually built');
p();
p('| Figure | In the deck | Provenance | How we know |');
p('|---|---|---|---|');
for (const a of [
  OPERATING.pageComponents,
  OPERATING.hooks,
  OPERATING.edgeFunctions,
  OPERATING.migrations,
  OPERATING.sourceFiles,
  OPERATING.tests,
  OPERATING.testFiles,
  OPERATING.burnMonthly,
]) {
  p(row(a, a.unit === 'USD/month' ? money(a.value) : count(a.value)));
}
p();
p('**"How do you know?"** — each of those is a shell command in the register, re-runnable');
p('in about a second. Offer to run one.');
p();

p('## Slide 8 — how the money works');
p();
p('| Figure | In the deck | Provenance | How we know |');
p('|---|---|---|---|');
for (const tier of ['starter', 'growth', 'pro'] as const) {
  p(row(PRICING[tier], money(PRICING[tier].value)));
}
for (const tier of ['free', 'pro'] as const) {
  p(row(TIER_TAKE_RATES[tier], pct(TIER_TAKE_RATES[tier].value * 100)));
}
p(row(MARKET.campaignsPerRestaurantPerMonth, String(MARKET.campaignsPerRestaurantPerMonth.value)));
p(row(MARKET.deliverablesPerCampaign, String(MARKET.deliverablesPerCampaign.value)));
p();
p(`Average campaign value **${money(avgCampaignValue())}** — the midpoint of the app's own`);
p(`standard band (${money(MARKET.campaignPriceStandardLow.value)}–${money(MARKET.campaignPriceStandardHigh.value)} a deliverable) times ${MARKET.deliverablesPerCampaign.value} deliverables.`);
p();
p(`At 100 restaurants: **${money(at100.totalRevenue)}/month** — ${money(at100.subscriptionRevenue)} subscription plus ${money(at100.takeRateRevenue)} take rate, on ${count(at100.campaigns)} campaigns worth ${money(at100.gmvDollars)}.`);
p();
p('**"Are the other two streams real?"** — AI overages and the DragonDash rush surcharge');
p('are live in the product and have never been charged, so they are valued at **$0** in');
p('every figure in the deck. Say that before being asked; it makes the two we do count');
p('easier to believe.');
p();

p('## Slide 9 — unit economics');
p();
p('| Figure | In the deck | Provenance | How we know |');
p('|---|---|---|---|');
p(row(UNIT_ECONOMICS.restaurantCacLow, money(UNIT_ECONOMICS.restaurantCacLow.value)));
p(row(UNIT_ECONOMICS.restaurantCacHigh, money(UNIT_ECONOMICS.restaurantCacHigh.value)));
p(row(UNIT_ECONOMICS.monthlyChurn, pct(UNIT_ECONOMICS.monthlyChurn.value * 100, 1)));
p();
p(`Gross profit per restaurant per month **${money(u.grossProfitPerBusinessPerMonth)}** (${pct(one.grossMarginPct, 1)} gross margin) · lifetime **${u.customerLifetimeMonths.toFixed(0)} months** · LTV **${money(u.ltv)}** · LTV:CAC **${u.ltvToCacAtCacHigh.toFixed(1)}–${u.ltvToCacAtCacLow.toFixed(1)}:1** · payback **${u.cacPaybackMonthsAtCacLow.toFixed(1)}–${u.cacPaybackMonthsAtCacHigh.toFixed(1)} months**.`);
p();
p('**"How do you know your CAC?"** — *We do not.* We have never acquired a paying');
p('customer. That band is a target from our own pricing work, so the ratio is honest');
p('arithmetic on two assumptions, not a measurement. What is solid is the cost side:');
p(`serving one more restaurant costs about ${money(UNIT_ECONOMICS.aiCostPerCustomerMonth.value + UNIT_ECONOMICS.infraCostPerCustomerMonth.value)} a month, which is why the margin holds at any scale.`);
p();

p('## Slide 10 — Hoboken liquidity');
p();
p(`Liquid means **≥ ${LIQUIDITY_THRESHOLD.minApplicantsPerCampaign} applicants per campaign** over the ${MARKET.campaignOpenDays.value} days it stays open, **and ≥ ${LIQUIDITY_THRESHOLD.minCampaignsVisibleToCreator} campaigns open** for a creator to choose from.`);
p();
p(`At 2 restaurants and ${2 * ratio} creators a month: **${liquidMonth === null ? 'never within 36 months' : `month ${liquidMonth}`}**.`);
p(`At 2 restaurants and only 4 creators a month: **${starvedMonth === null ? 'never liquid, at any restaurant count' : `month ${starvedMonth}`}**.`);
p();
p(`**"What if you are wrong?"** — the honest weak point: at the target ratio we clear the applicant threshold by ${(((isLiquid(1, ratio).applicantsPerCampaign - LIQUIDITY_THRESHOLD.minApplicantsPerCampaign) / isLiquid(1, ratio).applicantsPerCampaign) * 100).toFixed(0)}% — ${isLiquid(1, ratio).applicantsPerCampaign.toFixed(1)} against a floor of ${LIQUIDITY_THRESHOLD.minApplicantsPerCampaign.toFixed(1)} — and both inputs are modelled. Volunteer that. The defensible part is that the model can express a creator shortage at all, which is the failure mode that actually kills local marketplaces.`);
p();

p('## Slide 11 — 100 / 1,000 / 10,000 businesses');
p();
p('| Businesses | Creators | Campaign volume/mo | Revenue/mo | Revenue/yr | Gross margin |');
p('|---:|---:|---:|---:|---:|---:|');
for (const s of steps) {
  p(
    `| ${count(s.businesses)} | ${count(s.creators)} | ${moneyShort(s.monthlyGmv)} | ${moneyShort(s.monthlyRevenue)} | ${moneyShort(s.annualRevenue)} | ${pct(s.grossMarginPct, 1)} |`,
  );
}
p();
p(`Tier mix assumed: ${pct(MARKET.tierMixFree.value * 100)} free / ${pct(MARKET.tierMixStarter.value * 100)} starter / ${pct(MARKET.tierMixGrowth.value * 100)} growth / ${pct(MARKET.tierMixPro.value * 100)} pro — i.e. ${pct((1 - MARKET.tierMixFree.value) * 100)} of restaurants on a paid plan, from a base of zero today. \`MODELED\`, and it drives most of the revenue above.`);
p();
p(`**"Is churn in these numbers?"** — **No.** Churn is benchmarked at ${pct(UNIT_ECONOMICS.monthlyChurn.value * 100, 1)} a month and no formula applies a drag. This is what the business looks like holding that customer count, not a forecast net of leavers. Say so unprompted.`);
p();
p('**"How do you actually get the first ones?"** — ' + FOUNDER_FACTS.launchEvents.statement);
p(`Source: ${FOUNDER_FACTS.launchEvents.source}, ${FOUNDER_FACTS.launchEvents.asOf}. Dates, whether the`);
p('venues are booked, and the budget are **not settled**; the deck marks that on the slide.');
p();
p('Say what these are and what they are not. They are **events**, not three market launches: the');
p('metro sequence is Hoboken, then Manhattan, then Palm Beach, each gated on density before the');
p('next, and Montauk is a night rather than a market.');
p();
p('**The reason the three hang together is an argument, not a finding, and must be said that way.**');
p('The seasons are complementary and that part is just true of the towns — Montauk peaks in summer,');
p('Palm Beach in winter, Hoboken is year-round. What is *unmeasured* is the bit that matters: that');
p('our own Hoboken and New York network is the one that travels to both, so all three events feed');
p('one market rather than three. That is our reasoning for choosing these cities. We have not');
p('measured the overlap and should not imply we have — offer it as why we picked them, and if');
p('pressed, say plainly that the first event is what tests it.');
p();

p('## Slide 12 — the trajectory');
p();
// Built from `rollup()`, the SAME source slide 12 renders from — not from
// `threeYearTrajectory()`, which derives off the superseded top-down band. This block used to
// print a revenue band against a cost band, and slide 12 has not looked like that since it was
// rebuilt bottom-up: it shows one number per year. So a founder walking an investor through this
// crib sheet was reading figures that disagreed with the screen in front of them, which is the
// worst way for staleness to surface. Restated 2026-08-26.
p('**What slide 12 actually shows**, per year: revenue **booked** during the year (the bar), the');
p("metro contribution — that metro's own delivery and marketing cost netted off — and, in smaller");
p('type, exit ARR and the number of metros live.');
p();
p('| Year | Booked revenue | Metro contribution | Exit ARR | Metros live |');
p('|---|---|---|---|---|');
for (const y of rollup()) {
  p(
    `| ${y.year} | ${moneyShort(y.revenue)} | ${moneyShort(y.metroEbitda)} | ${moneyShort(y.exitArr)} | ${y.metrosLive} |`,
  );
}
p();
p('**Metro contribution is not EBITDA, and the difference matters if you are asked.** It nets only');
p('what the metros themselves cost. Shared costs — the team, the platform, everything not');
p('attributable to a metro — sit below it, and the consolidated line that includes them renders');
p('only on the confidential build. So a positive metro contribution does *not* mean the company is');
p('profitable that year.');
p();
// `threeYearTrajectory()` numbers its years 1/2/3; `rollup()` numbers them 2026/2027/2028. They
// are the same three years and joining them on `year` matches NOTHING — silently, since a `find`
// that fails just yields undefined. Paired by POSITION, and asserted, rather than by a key the two
// sources happen to spell differently.
if (years.length !== rollup().length) {
  console.error(
    `Refusing to generate: the cost trajectory has ${years.length} years and the rollup has ` +
      `${rollup().length}. They are paired by position, so a length mismatch would silently ` +
      'pair the wrong cost band with the wrong revenue.',
  );
  process.exit(1);
}
p('The registered all-in cost bands are unchanged:');
p(
  rollup()
    .map((r, i) => `**${r.year} ${moneyShort(years[i].totalCostLow)}–${moneyShort(years[i].totalCostHigh)}**`)
    .join(' · ') + '.',
);
p('Against booked revenue that is');
p(
  rollup()
    .map(
      (r, i) =>
        `**${r.year}: ${moneyShort(r.revenue - years[i].totalCostHigh)} to ${moneyShort(r.revenue - years[i].totalCostLow)}**`,
    )
    .join(' · ') + '.',
);
p();
p('Cost here is all-in — Stripe, AI, infrastructure, payroll, marketing, legal — so it is not');
p('comparable to the gross-margin figure on slide 9, which excludes everything below the');
p('gross-profit line. The pessimistic end of each range pairs our revenue with the **high** end of');
p('the cost band, which is not how most decks draw a downside. Point that out.');
p();

p('## Slide 13 — the fine-tune claim');
p();
p('**"Why is 1,000–5,000 the magic number?"** It is the right challenge, and the answer is');
p('that the number was defensible but the **unit** was wrong. A campaign is not one');
p('training example: it is a chain that yields a brief (intent), several applicants');
p('resolving to one hire (a preference pair), an approve-or-reject (a quality label) and a');
p('performance record (an outcome). A few thousand campaigns therefore produce tens of');
p('thousands of labelled preference pairs, which is the regime LoRA is sample-efficient');
p('in, at $50–300 a run. Nothing has been fine-tuned yet.');
p();

p('## Glossary — say the plain version first');
p();
p('| Term | Say this |');
p('|---|---|');
for (const g of GLOSSARY) p(`| ${cell(g.term)} | ${cell(g.gloss)} |`);
p();

if (OUTSTANDING.length > 0) {
  p('## Still outstanding — do not improvise these');
  p();
  p('The deck marks each of these on its slide. If asked, the honest answer is "not');
  p('settled yet", not a number invented in the room.');
  p();
  for (const i of OUTSTANDING) p(`- **${i.blocks}** — ${i.question}`);
  p();
}

writeFileSync(OUT, `${L.join('\n')}\n`);
console.log(`Wrote ${OUT} (${L.length} lines, ${OUTSTANDING.length} outstanding inputs flagged)`);
