// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import {
  classifySupabaseUrl,
  PROD_SUPABASE_HOST,
  STAGING_SUPABASE_HOST,
} from '@/lib/supabaseEnvGuard';

// The production Supabase project, built from the host the guard module owns so there
// is exactly one place this ref is written down.
const PROD_SUPABASE_URL = `https://${PROD_SUPABASE_HOST}`;

// Source the Supabase project from env (VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY)
// so non-prod surfaces — e.g. the Vercel staging preview for the QA/CI-CD gate —
// point at their own isolated backend. Falls back to the prod project when the env
// vars are unset (the Vercel Production scope sets them, so prod is unaffected). This
// keeps client.ts consistent with the edge-function callers that already read these vars.
export const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || PROD_SUPABASE_URL;
// Exported so guest-facing surfaces (e.g. the public package checkout) can invoke an edge function AS ANON
// even when a user is logged in — the public shareable link is a guest-checkout surface by design.
//
// Both names are accepted because the repo has historically disagreed with itself:
// `.env`/`.env.example` define VITE_SUPABASE_PUBLISHABLE_KEY while every call site reads
// VITE_SUPABASE_ANON_KEY. Accepting either is purely additive — no existing environment
// that works today stops working.
export const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvY2FoaWZmb29xZHliZGhndXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzgzMzQsImV4cCI6MjA2NTU1NDMzNH0.bGhT6ft_zTbw-9v2Typi0wxzlfStg3sGiuPOor8Wfz8";

// --- Local-development safety guard -----------------------------------------
//
// `npm run dev` used to connect to PRODUCTION. The tracked `.env` sets
// VITE_SUPABASE_URL to the prod project, and the fallback above is the prod project
// too, so a fresh clone reached live customer data with no warning and no opt-in.
// Survivable while one person ran it; unacceptable the moment anyone is hired.
//
// This throws at import time in `npm run dev` only. Production and preview builds
// (MODE 'production') and the vitest suite (MODE 'test') are untouched — their
// behaviour is byte-for-byte what it was before this guard existed.
//
// Need prod data locally? Opt in explicitly, per session, and know what you are doing:
//   VITE_ALLOW_PROD_FROM_LOCAL=true npm run dev
//
// The classification rule lives in `@/lib/supabaseEnvGuard` and is unit-tested there.
// It compares HOSTS, never whole strings: a trailing slash, different casing or an added
// path all describe the same project while failing an equality check, so a string
// comparison would fail OPEN — the worst way for a safety control to be wrong.
if (
  import.meta.env.DEV &&
  import.meta.env.MODE !== 'test' &&
  import.meta.env.VITE_ALLOW_PROD_FROM_LOCAL !== 'true'
) {
  const target = classifySupabaseUrl(SUPABASE_URL);

  if (target === 'unparseable') {
    // Fail closed: we cannot prove this is safe.
    throw new Error(
      `Refusing to start: VITE_SUPABASE_URL is not a valid URL (${JSON.stringify(SUPABASE_URL)}).\n` +
        'Set it in .env.local to the staging project:\n' +
        `  VITE_SUPABASE_URL=https://${STAGING_SUPABASE_HOST}`,
    );
  }

  if (target === 'production') {
    throw new Error(
      [
        'Refusing to start: local dev is pointed at the PRODUCTION Supabase project.',
        '',
        'Create a .env.local pointing at staging (this file is gitignored):',
        `  VITE_SUPABASE_URL=https://${STAGING_SUPABASE_HOST}`,
        '  VITE_SUPABASE_ANON_KEY=<staging anon key>',
        '',
        'See docs/onboarding/first-week.md. If you genuinely need production data',
        'locally, opt in for that session only:',
        '  VITE_ALLOW_PROD_FROM_LOCAL=true npm run dev',
      ].join('\n'),
    );
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// NOTE: types.ts is auto-generated and currently does not include several
// tables/columns/RPCs that have been added via newer migrations
// (organizations, org_members, account_deletion_requests, dismissed_coachmarks,
// transition_content_status RPC, etc.). Until types are regenerated, we type
// the client loosely so call sites compile. Runtime behavior is unchanged.
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- types.ts lags behind migrations; loosened intentionally
) as unknown as SupabaseClient<any, "public", any>;
